Tradeshift/http-mockserver

Dockerfile, src/controller.js, src/service.js
=> upgrade to node 6.9.1 and minor improvements

src/controller.js
=> Output as JSON

.eslintrc, package.json
=> Add ESLint

Dockerfile
=> Add bin folder to Dockerfile

package.json, src/server/requestLogService.js
If body is null it throws an error. This fixes it.
=> Fix nullpointer in toString

package.json, src/client/Client.js
=> MockClient should throw on request error

package.json, src/client/Client.js
Simple debug mode for MockClient
=> Add debug mode

src/server/Listener.js, src/server/listenerService.js
Make it possible to overwrite the existing route handler.
=> Dynamically change route handler

.dockerignore, .eslintrc, Dockerfile, __tests__/examples.test.js, __tests__/mockClient.test.js, docker-build-and-push.sh, examples/dynamic-mock.js, examples/static-mock.json, package.json, src/server/Listener.js, test.sh
- Add Jest (testing framework, similar to Jasmine)
- Add Docker script (will replace the script in Jenkins)
- Update examples
=> Add Jest test harness

package.json
=> Bump to 1.1.6

docker/push.sh, docker/test.sh, jenkins/jenkins-ghprb.sh, jenkins/jenkins-master.sh
Exactly the same as https://github.com/Tradeshift/collaboration-backend/pull/374, just for http-mockserver.
=> Tag Docker image with “latest” tag

package.json, src/server/Listener.js
be liberal in what you accept from others.
still needs version bump.
=> Add text body parser and liberalize JSON body parser

src/server/listenerService.js
Throw if http method is invalid.
=> Validate http method

src/server/Listener.js
When overriding mocks that have pending requests, those requests stay open but those requests will never receive data after overriding. 
=> close pending requests when overriding existing mock

package.json, src/server/Listener.js
Mocking the creating virtual card request in GO requires xml parser.
=> GO-360 Add xml body parser and bump version

package-lock.json, package.json
[ZTN-4688] Bump lodash from 4.17.20 to 4.17.21
[ZTN-4688]: https://tradeshift.atlassian.net/browse/ZTN-4688
=> [ZTN-4688] Bump lodash from 4.17.20 to 4.17.21

package-lock.json
=> Fix ZTN-4685

__tests__/e2e.test.js, __tests__/examples.test.js, package-lock.json, package.json
bump jest from 18.0.1 to 27.0.3
=> bump jest from 18.0.1 to 27.0.3

package-lock.json, package.json
=> Fix ZTN-4860

package-lock.json, package.json
=> Fix more Dependabots

package-lock.json, package.json
VULN-2737 - [http-mockserver] minimist has vulnerabilities
=> VULN-2737 - [http-mockserver] minimist has vulnerabilities

package-lock.json, package.json
=> Fix json-schema vulnerability

.github/workflows/main.yml, .github/workflows/npm-publish.yml, jenkins/jenkins-master.sh
fix(token): change the token for npm
=> fix(token): change the token for npm

.github/dependabot.yml, .github/workflows/main.yml, .github/workflows/pr-sonar.yml, Dockerfile, jenkins/jenkins-master.sh
=> TRAN-3592 use AWS docker repo

.github/workflows/main.yml
=> TRAN-3592 fix AWS docker repo

.github/renovate.json
TRAN-3669 Renovate phase 2 configure all owned repos for auto merge
=> TRAN-3669 Renovate phase 2 configure all owned repos for auto merge
